# fly.toml app configuration file generated for rably on 2025-06-25T15:37:43+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rably'
primary_region = 'bom'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  image = 'ghcr.io/rovierrhq/rably:slim'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
