app = 'rably'
primary_region = 'sjc'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  image = 'rably:slim'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 10

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 800

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[env]
  PORT = "8080"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512